### ISSUE TITLE
Controls color inheritance and width adjustment issues

### ISSUE THREAD

**Issue by zeitbit** [stepan-mitkin/drakonhub_desktop#2]
It seems that there are two small issues: the controls timer, pause, start/end control period, callout and group duration do not inherit the global color set in "diagram format", and the controls input, output, self and parallel process do not adjust their width correctly according to their text.
Also, when trying to increase the width of any control, it doesn't let you do it properly because it really limits the allowed width.

Version: 2024.10.05

![test](https://github.com/user-attachments/assets/e8dbf0da-e2fb-4721-9b02-d952c4c09003)

**Comment by stepan-mitkin** [comment]
> the controls timer, pause, start/end control period, callout and group duration do not inherit the global color set in "diagram format"

It's a feature. These icons obey the theme, not the diagram format. You can, however, set the colors of an individual icon.

> the controls input, output, self and parallel process do not adjust their width correctly according to their text.

Fixed.

> when trying to increase the width of any control, it doesn't let you do it properly because it really limits the allowed width

Fixed.
